ldap_debconf:
  - { question: "slapd/internal/adminpw", value: "{{ ldap_admin_password }}", vtype: "password" }
  - { question: "slapd/internal/generated_adminpw", value: "{{ ldap_admin_password }}", vtype: "password" }
  - { question: "slapd/password1", value: "{{ ldap_admin_password }}", vtype: "password" }
  - { question: "slapd/password2", value: "{{ ldap_admin_password }}", vtype: "password" }
  - { question: "slapd/domain", value: "{{ ldap_domain }}", vtype: "string" }
  - { question: "shared/organization", value: "{{ ldap_org }}", vtype: "string" }
  - { question: "slapd/no_configuration", value: "false", vtype: "boolean" }

